services:
  discordbot:
    build: .
    volumes:
      - ./data:/app/data
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 100M
        reservations:
          cpus: '0.3'
          memory: 100M